var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "DiamondBoard", "class_diamond_board.html", "class_diamond_board" ],
    [ "DiamondUI", "class_diamond_u_i.html", "class_diamond_u_i" ],
    [ "FiveByFive_Board", "class_five_by_five___board.html", "class_five_by_five___board" ],
    [ "FiveByFive_UI", "class_five_by_five___u_i.html", "class_five_by_five___u_i" ],
    [ "FourInARow_Board", "class_four_in_a_row___board.html", "class_four_in_a_row___board" ],
    [ "FourInARow_Move", "class_four_in_a_row___move.html", "class_four_in_a_row___move" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_Board", "class_infinity___board.html", "class_infinity___board" ],
    [ "Misere_XO_Board", "class_misere___x_o___board.html", "class_misere___x_o___board" ],
    [ "Misere_XO_UI", "class_misere___x_o___u_i.html", "class_misere___x_o___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "NumericalBoard", "class_numerical_board.html", "class_numerical_board" ],
    [ "NumericalUI", "class_numerical_u_i.html", "class_numerical_u_i" ],
    [ "ObstaclesTTT_Board", "class_obstacles_t_t_t___board.html", "class_obstacles_t_t_t___board" ],
    [ "ObstaclesTTT_Move", "class_obstacles_t_t_t___move.html", "class_obstacles_t_t_t___move" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Pyramid_Board", "class_pyramid___board.html", "class_pyramid___board" ],
    [ "SUS_Board", "class_s_u_s___board.html", "class_s_u_s___board" ],
    [ "SUS_Move", "class_s_u_s___move.html", "class_s_u_s___move" ],
    [ "TicTacToe4x4_Board", "class_tic_tac_toe4x4___board.html", "class_tic_tac_toe4x4___board" ],
    [ "TicTacToe4x4_UI", "class_tic_tac_toe4x4___u_i.html", "class_tic_tac_toe4x4___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "WordGame_UI", "class_word_game___u_i.html", "class_word_game___u_i" ],
    [ "WordTae_Board", "class_word_tae___board.html", "class_word_tae___board" ],
    [ "X_O_Board", "class_x___o___board.html", "class_x___o___board" ],
    [ "XO_UI", "class_x_o___u_i.html", "class_x_o___u_i" ]
];